[workspace]
members = ["messages", "opcua-client", "redis-client", "webapp"]


[workspace.dependencies]
leptos = { version = "0.5.0-beta", features = ["csr", "tracing"] }
opcua = { version = "0.11", features = ["client"] }
redis = { version = "0.23.2", features = ["tokio-comp"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tracing = { version = "0.1" }
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
tokio = { version = "1", features = ["full"] }
