[workspace]
members = ["redis-client"]


[workspace.dependencies]
redis = { version = "0.23.2", features = ["tokio-comp"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1", features = ["full"] }
