version: "3.8"
name: demo_siemens_to_web

networks:
  loki:

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "8010:8001"

  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:2.9.0
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - LOKI_PORT=${LOKI_PORT}
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./services/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - loki

  db:
    container_name: db
    hostname: db
    command: postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: timescale/timescaledb:2.11.2-pg15
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./services/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./services/db/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_volume:
    name: db_volume
