[package]
name = "redis-client"
version = "0.0.1"
edition = "2021"


[dependencies]
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
ntest = { workspace = true }
