[package]
name = "webapp-lib"
version = "0.0.1"
edition = "2021"

[dependencies]
gloo = { workspace = true }
futures-util = { workspace = true }
url = { workspace = true }
web-sys = { workspace = true }
