[package]
name = "webapp"
version = "0.0.1"
edition = "2021"


[dependencies]
gloo = { workspace = true }
leptos = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

messages = { workspace = true }
